apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Postgres database for various data.
  labels:
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: pgsql
  name: pgsql
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploy: sourcegraph
        app: pgsql
        group: backend
    spec:
      initContainers:
      - name: correct-data-dir-permissions
        image: index.docker.io/sourcegraph/alpine-3.12:insiders@sha256:dbe2829a9438852c5a4696d0574ecffcf9cc01edb91830241ae547e60d5ebc28
        command: ["sh", "-c", "if [ -d /data/pgdata-12 ]; then chmod 750 /data/pgdata-12; fi"]
        volumeMounts:
        - mountPath: /data
          name: disk
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: "10m"
            memory: "50Mi"
          requests:
            cpu: "10m"
            memory: "50Mi"
      containers:
      - env:
        image: index.docker.io/sourcegraph/postgres-12.6:3.29.0@sha256:cf3eb6a0a6e61a3dfab2394e01565ecb49082f40fd616210bf6a843fa8e82be6
        terminationMessagePolicy: FallbackToLogsOnError
        readinessProbe:
          exec:
            command:
              - /ready.sh
        livenessProbe:
          initialDelaySeconds: 15
          exec:
            command:
              - /liveness.sh
        name: pgsql
        ports:
        - containerPort: 5432
          name: pgsql
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "4"
            memory: 4Gi
        volumeMounts:
        - mountPath: /data
          name: disk
        - mountPath: /conf
          name: pgsql-conf
      - env:
        - name: DATA_SOURCE_NAME
          value: postgres://sg:@localhost:5432/?sslmode=disable
        - name: PG_EXPORTER_EXTEND_QUERY_PATH
          value: /config/queries.yaml
        image: index.docker.io/sourcegraph/postgres_exporter:3.29.0@sha256:6b2525f8e9c33d64ddcfafca637c8e1f81e30b89eb907ea7e894bd18651e31e8
        terminationMessagePolicy: FallbackToLogsOnError
        name: pgsql-exporter
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 50Mi
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsUser: 0
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: pgsql
      - name: pgsql-conf
        configMap:
          defaultMode: 0777
          name: pgsql-conf
